name: Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: build and test cadc-dali
      run: cd cadc-dali && ../gradlew --info clean build javadoc checkstyleMain install
      
# cadc-dali-pg is not yet cleanup to pass checkstyleMain
    - name: build and test cadc-dali-pg
      run: cd cadc-dali-pg && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-sia
      run: cd cadc-sia && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-conesearch
      run: cd cadc-conesearch && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-datalink
      run: cd cadc-datalink && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-datalink-server
      run: cd cadc-datalink-server && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-pkg-server
      run: cd cadc-pkg-server && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test cadc-soda-server
      run: cd cadc-soda-server && ../gradlew --info clean build javadoc checkstyleMain install

    - name: install wcslib-5.15 from source (ugh)
      run: |
        sudo apt-get update && sudo apt-get install -y curl gcc make \
        && curl -Lv -o /tmp/wcslib.tar.bz2 https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/wcslib/5.15-1/wcslib_5.15.orig.tar.bz2 \
        && cd /tmp/ \
        && tar jxvf wcslib.tar.bz2 \
        && cd wcslib-5.15 \
        && ./configure --prefix=/usr \
        && make && sudo make install

    - name: build and test cadc-data-ops-fits
      run: cd cadc-data-ops-fits && ../gradlew --info clean build javadoc checkstyleMain install
